---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-local-cache-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: local-ebs://dev/xvdbz
    volumeAttributes:
      ebs.csi.aws.com/fsType: "xfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-local-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: node-local-cache-pv