apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_USER: d29yZHByZXNz
  MYSQL_PASSWORD: cGFzc3dvcmQ=